import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const handleClick = () => {
    router.push("/docs");
    //router.replace("...")
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen px-8 py-16 bg-zinc-100'>
        <h1 className='font-semibold text-center cursor-pointer text-zinc-800 hover:text-indigo-500 text-7xl'>
          NEXT.js
        </h1>
        <Link href='/blog' className='block text-xl font-semibold text-blue-700 hover:underline'>
          Blog
        </Link>
        <button
          onClick={handleClick}
          className='block px-3 py-2 mt-2 text-xl font-semibold text-blue-700 border border-blue-700 hover:bg-blue-50 rounded-xl border-1'
        >
          View Docs
        </button>
        <Link href='/static-generation' className='block text-xl link'>
          Static Generation with getStaticProps
        </Link>
        <Link href='/posts' className='block text-xl link'>
          Posts (Dynamic SSG)
        </Link>
        <Link href='/products' className='block text-xl link'>
          Products (ISR)
        </Link>
        <Link href='/news' className='block text-xl link'>
          News (SSR)
        </Link>
        <Link href='/dashboard' className='block text-xl link'>
          Dashboard (Client-side Data fetching)
        </Link>
        <Link href='/dashboard/dashboard-swr' className='block text-xl link'>
          Dashboard (Client-side Data fetching with SWR)
        </Link>
        <Link href='/events' className='block text-xl link'>
          Events (Pre-rendering + client side Data Fetching)
        </Link>
        <h2 className='mt-4 text-xl font-bold'>API</h2>
        <Link href='/comments' className='block text-xl link'>
          Comments (GET/POST/DELETE)
        </Link>
        <h2 className='mt-4 text-xl font-bold'>MEMO</h2>
        <Link href='/memo' className='block text-xl link'>
          Memo
        </Link>
        <h2 className='mt-4 text-xl font-bold'>Image</h2>
        <Link href='/pets' className='block text-xl link'>
          Pets
        </Link>
        <h2 className='mt-4 text-xl font-bold'>Auth</h2>
        <Link href='/auth' className='block text-xl link'>
          Auth
        </Link>
      </main>
    </>
  );
}
